In [1]:
import pandas as pd
from ast import literal_eval
import numpy as np


In [2]:
movies_metadata = pd.read_csv("data/movies_metadata.csv")
movies_metadata.shape

C:\TempFolder\ipykernel_24408\1855133637.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies_metadata = pd.read_csv("data/movies_metadata.csv")


(45466, 24)

In [3]:

movies_metadata.head()
movies_metadata['genres'].head()

0    [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1    [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2    [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3    [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                       [{'id': 35, 'name': 'Comedy'}]
Name: genres, dtype: object

In [4]:
print(movies_metadata['genres'][0])

[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]


In [5]:
movies_metadata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   adult                  45466 non-null  object 
 1   belongs_to_collection  4494 non-null   object 
 2   budget                 45466 non-null  object 
 3   genres                 45466 non-null  object 
 4   homepage               7782 non-null   object 
 5   id                     45466 non-null  object 
 6   imdb_id                45449 non-null  object 
 7   original_language      45455 non-null  object 
 8   original_title         45466 non-null  object 
 9   overview               44512 non-null  object 
 10  popularity             45461 non-null  object 
 11  poster_path            45080 non-null  object 
 12  production_companies   45463 non-null  object 
 13  production_countries   45463 non-null  object 
 14  release_date           45379 non-null  object 
 15  re

In [6]:
links_small = pd.read_csv("data/links_small.csv")
links_small.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9125 entries, 0 to 9124
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   movieId  9125 non-null   int64  
 1   imdbId   9125 non-null   int64  
 2   tmdbId   9112 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 214.0 KB


In [7]:
links_small = links_small[links_small['tmdbId'].notnull()]['tmdbId'].astype('int')
links_small.shape

(9112,)

In [8]:
links_small.info()

<class 'pandas.core.series.Series'>
Index: 9112 entries, 0 to 9124
Series name: tmdbId
Non-Null Count  Dtype
--------------  -----
9112 non-null   int64
dtypes: int64(1)
memory usage: 142.4 KB


In [9]:
movies_metadata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   adult                  45466 non-null  object 
 1   belongs_to_collection  4494 non-null   object 
 2   budget                 45466 non-null  object 
 3   genres                 45466 non-null  object 
 4   homepage               7782 non-null   object 
 5   id                     45466 non-null  object 
 6   imdb_id                45449 non-null  object 
 7   original_language      45455 non-null  object 
 8   original_title         45466 non-null  object 
 9   overview               44512 non-null  object 
 10  popularity             45461 non-null  object 
 11  poster_path            45080 non-null  object 
 12  production_companies   45463 non-null  object 
 13  production_countries   45463 non-null  object 
 14  release_date           45379 non-null  object 
 15  re

In [10]:

# movies_metadata['id'].isin(links_small.astype('str'))
movies_metadata_small= movies_metadata[movies_metadata['id'].isin(links_small.astype('str'))]
movies_metadata_small.shape

(9099, 24)

In [11]:
# movies = movies_metadata_small['title']
movies = movies_metadata_small[['title','popularity','genres','release_date']]
movies.head()

title popularity  \
0                    Toy Story  21.946943   
1                      Jumanji  17.015539   
2             Grumpier Old Men    11.7129   
3            Waiting to Exhale   3.859495   
4  Father of the Bride Part II   8.387519   

                                              genres release_date  
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   1995-10-30  
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   1995-12-15  
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   1995-12-22  
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   1995-12-22  
4                     [{'id': 35, 'name': 'Comedy'}]   1995-02-10

In [12]:
movies.head(1)

title popularity                                             genres  \
0  Toy Story  21.946943  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   

  release_date  
0   1995-10-30

In [13]:
# print(movies.iloc[0]['genres'])
# print(movies.loc[0,'title'])
print(movies.loc[0,['title','genres']])

title                                             Toy Story
genres    [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
Name: 0, dtype: object


In [61]:
movies['genres'].loc[0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [14]:
df = pd.DataFrame({
    "math":[80,90,100],
    "eng":[75,85,95]
})

In [15]:
df.apply(lambda x:x.mean())

math    90.0
eng     85.0
dtype: float64

In [16]:
# movies['genres'].fillna('[]').apply(literal_eval).apply(lambda x: 참 if 조건 else 거짓 )

# test_list = movies['genres'].fillna('[]').apply(literal_eval).apply(lambda x: sorted(i['name'] for i in x ) if isinstance(x, list) else [] )


movies['str_genres'] = \
movies['genres'].fillna('[]').apply(literal_eval)\
    .apply(lambda x: sorted(i['name'] for i in x ) if isinstance(x, list) else [] )\
    .apply(lambda x : " ".join(x) if len(x)>0 else None)




C:\TempFolder\ipykernel_24408\143773636.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['str_genres'] = \


In [17]:
movies.head()

title popularity  \
0                    Toy Story  21.946943   
1                      Jumanji  17.015539   
2             Grumpier Old Men    11.7129   
3            Waiting to Exhale   3.859495   
4  Father of the Bride Part II   8.387519   

                                              genres release_date  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   1995-10-30   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   1995-12-15   
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   1995-12-22   
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   1995-12-22   
4                     [{'id': 35, 'name': 'Comedy'}]   1995-02-10   

                 str_genres  
0   Animation Comedy Family  
1  Adventure Family Fantasy  
2            Comedy Romance  
3      Comedy Drama Romance  
4                    Comedy

In [18]:
movies['release_date'] = pd.to_datetime(movies['release_date'])

C:\TempFolder\ipykernel_24408\1211608248.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['release_date'] = pd.to_datetime(movies['release_date'])


In [19]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9099 entries, 0 to 45265
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   title         9099 non-null   object        
 1   popularity    9099 non-null   object        
 2   genres        9099 non-null   object        
 3   release_date  9099 non-null   datetime64[ns]
 4   str_genres    9064 non-null   object        
dtypes: datetime64[ns](1), object(4)
memory usage: 684.6+ KB


In [20]:
movies['year'] = movies['release_date'].dt.year
movies[['release_date', 'year']]

C:\TempFolder\ipykernel_24408\1038786292.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['year'] = movies['release_date'].dt.year


release_date  year
0       1995-10-30  1995
1       1995-12-15  1995
2       1995-12-22  1995
3       1995-12-22  1995
4       1995-02-10  1995
...            ...   ...
40224   2016-07-29  2016
40503   2016-09-15  2016
44821   2000-07-08  2000
44826   2001-07-06  2001
45265   2014-08-15  2014

[9099 rows x 2 columns]

In [21]:
# movies.isnull().sum() 
# movies.shape

(movies.isnull().sum() / movies.shape[0] )

title           0.000000
popularity      0.000000
genres          0.000000
release_date    0.000000
str_genres      0.003847
year            0.000000
dtype: float64

In [22]:
movies = movies.dropna()
movies.reset_index(drop=True)

title popularity  \
0                                             Toy Story  21.946943   
1                                               Jumanji  17.015539   
2                                      Grumpier Old Men    11.7129   
3                                     Waiting to Exhale   3.859495   
4                           Father of the Bride Part II   8.387519   
...                                                 ...        ...   
9059                                      Shin Godzilla   9.285519   
9060  The Beatles: Eight Days a Week - The Touring Y...   7.078301   
9061                      Pokémon: Spell of the Unknown   6.480376   
9062        Pokémon 4Ever: Celebi - Voice of the Forest   6.080108   
9063                                      Force Majeure  12.165685   

                                                 genres release_date  \
0     [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   1995-10-30   
1     [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   1995-12-15   
2     [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   1995-12-22   
3     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   1995-12-22   
4                        [{'id': 35, 'name': 'Comedy'}]   1995-02-10   
...                                                 ...          ...   
9059  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   2016-07-29   
9060  [{'id': 99, 'name': 'Documentary'}, {'id': 104...   2016-09-15   
9061  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   2000-07-08   
9062  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   2001-07-06   
9063  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   2014-08-15   

                                             str_genres  year  
0                               Animation Comedy Family  1995  
1                              Adventure Family Fantasy  1995  
2                                        Comedy Romance  1995  
3                                  Comedy Drama Romance  1995  
4                                                Comedy  1995  
...                                                 ...   ...  
9059      Action Adventure Drama Horror Science Fiction  2016  
9060                                  Documentary Music  2016  
9061          Action Adventure Animation Family Fantasy  2000  
9062  Adventure Animation Family Fantasy Science Fic...  2001  
9063                                       Comedy Drama  2014  

[9064 rows x 6 columns]

In [23]:
movies.isnull().sum()

title           0
popularity      0
genres          0
release_date    0
str_genres      0
year            0
dtype: int64

In [24]:
## bow기반 content based filltering

from sklearn.feature_extraction.text import CountVectorizer


In [25]:
bow_vecter = CountVectorizer()

In [26]:
genre_mat = bow_vecter.fit_transform(movies['str_genres'])

In [27]:
bow_vecter.vocabulary_

{'animation': 2,
 'comedy': 3,
 'family': 7,
 'adventure': 1,
 'fantasy': 8,
 'romance': 16,
 'drama': 6,
 'action': 0,
 'crime': 4,
 'thriller': 18,
 'horror': 12,
 'history': 11,
 'science': 17,
 'fiction': 9,
 'mystery': 15,
 'war': 20,
 'foreign': 10,
 'music': 14,
 'documentary': 5,
 'western': 21,
 'tv': 19,
 'movie': 13}

In [28]:
genre_mat.shape

(9064, 22)

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
similarity_of_genre = cosine_similarity(genre_mat, genre_mat)

In [31]:
similarity_of_genre

array([[1.        , 0.33333333, 0.40824829, ..., 0.51639778, 0.47140452,
        0.40824829],
       [0.33333333, 1.        , 0.        , ..., 0.77459667, 0.70710678,
        0.        ],
       [0.40824829, 0.        , 1.        , ..., 0.        , 0.        ,
        0.5       ],
       ...,
       [0.51639778, 0.77459667, 0.        , ..., 1.        , 0.73029674,
        0.        ],
       [0.47140452, 0.70710678, 0.        , ..., 0.73029674, 1.        ,
        0.        ],
       [0.40824829, 0.        , 0.5       , ..., 0.        , 0.        ,
        1.        ]], shape=(9064, 9064))

In [32]:
a = np.array([30,40,51,47,40])
index = np.argsort(a)
index

array([0, 1, 4, 3, 2])

In [33]:
movie0_similarity = similarity_of_genre[0]

In [34]:
movie0_similarity

array([1.        , 0.33333333, 0.40824829, ..., 0.51639778, 0.47140452,
       0.40824829], shape=(9064,))

In [35]:
movies[['title', 'str_genres']].iloc[0:2,:]

title                str_genres
0  Toy Story   Animation Comedy Family
1    Jumanji  Adventure Family Fantasy

In [36]:
sorted_similarity_of_genre = similarity_of_genre.argsort()
sorted_similarity_of_genre

array([[  38, 7848, 9060, ..., 2718, 7064,    0],
       [ 926, 9054, 9063, ..., 8327, 5010,    1],
       [  58,   73, 9059, ...,    6,   49,   60],
       ...,
       [9060,   60,   61, ..., 9061, 3358, 7904],
       [9040, 9054, 9060, ..., 3020, 4340, 4238],
       [3400, 9042, 9043, ..., 6537, 3404, 3394]], shape=(9064, 9064))

In [37]:
sorted_similarity_of_genre[:,::-1]

array([[   0, 7064, 2718, ..., 9060, 7848,   38],
       [   1, 5010, 8327, ..., 9063, 9054,  926],
       [  60,   49,    6, ..., 9059,   73,   58],
       ...,
       [7904, 3358, 9061, ...,   61,   60, 9060],
       [4238, 4340, 3020, ..., 9060, 9054, 9040],
       [3394, 3404, 6537, ..., 9043, 9042, 3400]], shape=(9064, 9064))

In [38]:
movies[['title', 'str_genres']].iloc[[0,38],:]

title               str_genres
0                  Toy Story  Animation Comedy Family
39  Cry, the Beloved Country                    Drama