In [3]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)


[1 2 3 4 5]


In [ ]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
arr2 = np.array([1,2,3,4,5])
print(arr1[1])
print(arr1[1:4])

2
[2 3 4]


In [12]:
arr4 = np.array([1,2,3,4,5,6])
arr5 = arr4.reshape(1,6)
print(arr5)

[[1 2 3 4 5 6]]


In [17]:
x1 = [1,2,3,4]
y2 = [4,5,6,7]

print(x1+y2)

[1, 2, 3, 4, 4, 5, 6, 7]


In [19]:
arr11 = np.array(x1)
arr12 = np.array(y2)

print(arr11*arr12)

[ 4 10 18 28]


In [21]:
print(arr11.dtype)

int64


In [27]:
arr13 = np.array([1,2,3])
print(arr13.dtype)


arr13_float = arr13.astype('float64')
print(arr13_float)
print(arr13_float.dtype)

int64
[1. 2. 3.]
float64


In [43]:
arr14 = np.arange(12)
print(arr14, arr14.dtype)

arr15 = arr14.reshape(3,-1)
print(arr15)




[ 0  1  2  3  4  5  6  7  8  9 10 11] int64
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [50]:
arr20 = np.arange(1,10)
print(arr20)

arr21 = arr20.reshape(3,3)
print(arr21)


#[0:2, 0:2] 
arr31 = arr21[0:2, 0:2]
print(arr31, arr31.shape)

#[1:3, 0:3]
#[1:3, :]
#[:,:]
#[:2, :1]
#[:2,0]


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]] (2, 2)


In [62]:
import numpy as np

list1 = [1,2,3]
print(type(list1))

arr101 = np.array(list1)
print(list1)
print(arr101)
print(arr101.shape)

<class 'list'>
[1, 2, 3]
[1 2 3]
(3,)


In [66]:

arr102 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr102)
print(type(arr102))
print(arr102.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [75]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [82]:
arr111 = np.arange(10)
print(arr111)

arr112 = arr111.reshape(2,5)
print(arr112)

arr113 = arr112.reshape(-1)
print(arr113)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
array119 = np.arange(start=1, stop=10)
print(array119)

val = array119[0]
print(val)
print(type(val))



[1 2 3 4 5 6 7 8 9]
1
<class 'numpy.int64'>


In [109]:
#동물별 평균 체온과 최대 체중 구하기
import numpy as np

#체온, 심박수, 체중(kg)
data = np.array([
    [38.5, 80, 35], #dog
    [39.1, 90, 50], #cat
    [36.8, 60, 300], #holes

])

ani = np.array(["dog","cat","holes"])

#체온, 심박수, 체중의 평균값
# avg_value = data.mean(axis=1)
avg_value = data.min(axis=0)
print(avg_value)

weight = data[:,2]
print(weight)

max_weight = data[:,2].max()
print(max_weight)

max_ani = ani[data[:, 2].argmax()]
print(max_ani)

print("동물별 평균 수치", avg_value.astype(int))
print("가장 무거운 동물", max_ani, f'{max_weight}kg')


[36.8 60.  35. ]
[ 35.  50. 300.]
300.0
holes
동물별 평균 수치 [36 60 35]
가장 무거운 동물 holes 300.0kg


In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [118]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [124]:
#동물별 평균 체온과 최대 체중 구하기 

import numpy as np 
# #체온, 심박수, 체중(kg) 
data = np.array([ 
    [38.5, 80, 35], #dog 
    [39.1, 90, 50], #cat 
    [36.8, 60, 300], #holes
]) 

ani = np.array(["dog","cat","holes"])



#체온, 심박수, 체중의 평균값
# avg_value = data.mean(axis=1)
avg_value = data.min(axis=0)
print(avg_value)

weight = data[:,2]
print(weight)

max_weight = data[:,2].max()
print(max_weight)

[36.8 60.  35. ]
[ 35.  50. 300.]
300.0


In [123]:
import numpy as np

# 곤충 [날개 수, 다리 수, 몸 길이(cm)]
data = np.array([
    [2, 6, 1.2],
    [4, 6, 3.4],
    [0, 6, 0.8],
    [0, 8, 2.0]
])

insects = np.array(["나비", "잠자리", "개미", "거미"])

# 다리가 6개인 곤충 추출
legs = data[data[:, 1] == 6]
print(legs)

#평균 몸 길이
mean_length = data[:,2].mean()
print(mean_length)
print(f'곤충 평균 몸 길이 : {round(mean_length,2)} cm' )

#날개 없는 동물
no_wings = insects[data[:,0] == 0]
print(no_wings)


[[2.  6.  1.2]
 [4.  6.  3.4]
 [0.  6.  0.8]]
1.8499999999999999
곤충 평균 몸 길이 : 1.85 cm
['개미' '거미']


In [6]:
import numpy as np
arr1111 = np.arange(8)
arr3d = arr1111.reshape((2,2,2))
print(arr1111)
print(arr3d)
print(arr3d.tolist())

[0 1 2 3 4 5 6 7]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [11]:
arr55 = arr3d.reshape(-1,1)
print(arr55)
print(arr55.tolist())
print(arr55.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)
