In [3]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)


[1 2 3 4 5]


In [ ]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
arr2 = np.array([1,2,3,4,5])
print(arr1[1])
print(arr1[1:4])

2
[2 3 4]


In [12]:
arr4 = np.array([1,2,3,4,5,6])
arr5 = arr4.reshape(1,6)
print(arr5)

[[1 2 3 4 5 6]]
