In [3]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)


[1 2 3 4 5]


In [ ]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
arr2 = np.array([1,2,3,4,5])
print(arr1[1])
print(arr1[1:4])

2
[2 3 4]


In [12]:
arr4 = np.array([1,2,3,4,5,6])
arr5 = arr4.reshape(1,6)
print(arr5)

[[1 2 3 4 5 6]]


In [17]:
x1 = [1,2,3,4]
y2 = [4,5,6,7]

print(x1+y2)

[1, 2, 3, 4, 4, 5, 6, 7]


In [19]:
arr11 = np.array(x1)
arr12 = np.array(y2)

print(arr11*arr12)

[ 4 10 18 28]


In [21]:
print(arr11.dtype)

int64


In [27]:
arr13 = np.array([1,2,3])
print(arr13.dtype)


arr13_float = arr13.astype('float64')
print(arr13_float)
print(arr13_float.dtype)

int64
[1. 2. 3.]
float64


In [43]:
arr14 = np.arange(12)
print(arr14, arr14.dtype)

arr15 = arr14.reshape(3,-1)
print(arr15)




[ 0  1  2  3  4  5  6  7  8  9 10 11] int64
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [50]:
arr20 = np.arange(1,10)
print(arr20)

arr21 = arr20.reshape(3,3)
print(arr21)


#[0:2, 0:2] 
arr31 = arr21[0:2, 0:2]
print(arr31, arr31.shape)

#[1:3, 0:3]
#[1:3, :]
#[:,:]
#[:2, :1]
#[:2,0]


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]] (2, 2)


In [62]:
import numpy as np

list1 = [1,2,3]
print(type(list1))

arr101 = np.array(list1)
print(list1)
print(arr101)
print(arr101.shape)

<class 'list'>
[1, 2, 3]
[1 2 3]
(3,)


In [66]:

arr102 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr102)
print(type(arr102))
print(arr102.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [75]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [82]:
arr111 = np.arange(10)
print(arr111)

arr112 = arr111.reshape(2,5)
print(arr112)

arr113 = arr112.reshape(-1)
print(arr113)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
array119 = np.arange(start=1, stop=10)
print(array119)

val = array119[0]
print(val)
print(type(val))



[1 2 3 4 5 6 7 8 9]
1
<class 'numpy.int64'>
